### ISSUE TITLE
RuntimeError: CUDA error: initialization error

### ISSUE THREAD

**Issue by daquilnp** [princewang1994/TextSnake.pytorch#11]
Hello, 

When trying to run
`CUDA_VISIBLE_DEVICES=0 python train.py train_testy`
I get the following error:
```
Traceback (most recent call last):
  File "train.py", line 157, in <module>
    main()
  File "train.py", line 143, in main
    train(model, train_loader, criterion, scheduler, optimizer, epoch)
  File "train.py", line 45, in train
    for i, (img, train_mask, tr_mask, tcl_mask, radius_map, sin_map, cos_map, meta) in enumerate(train_loader):
  File "/home/anaconda3/envs/text_snake_env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 513, in __next__
    return self._process_next_batch(batch)
  File "/home/anaconda3/envs/text_snake_env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 534, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/anaconda3/envs/text_snake_env/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/anaconda3/envs/text_snake_env/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 66, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/anaconda3/envs/text_snake_env/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 66, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/anaconda3/envs/text_snake_env/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 63, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/home/anaconda3/envs/text_snake_env/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 63, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/home/anaconda3/envs/text_snake_env/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 59, in default_collate
    return torch.tensor(batch)
RuntimeError: CUDA error: initialization error
```
It looks like it has something to do with `enumerator(train_loader)`

**Comment by daquilnp** [comment]
It seems like I fixed the issue by making --num_workers=0, I assume this is a PyTorch issue with multiprocessing

**Comment by smartcatdog** [comment]
if you want to run code under multi process, or --num_workers > 1,
it could solved by setting
```
import multiprocessing as mp 
mp.set_start_method('spawn')
```
before run the main code
